language: node_js
deploy:
  api_key:
    secure: WTj1rDAVLc+pzouu4lLOtYIm0exAQwLbCVCUhd17MAp8+qMb+GRKZv/8E5v3N0iVucMj7ac1lwuDajwgUX89k059++Of25kPsw2f5vJQhm5MhzXaXL5mo4aB/O149hLdl/VdSXx9zuqRhPwdXJOnnUcwLK0opmMfYp1V5oRSywI=
  provider: npm
  email: john@mclear.co.uk
